// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyProviderProfile(arg1) {
  return window['go']['main']['App']['ApplyProviderProfile'](arg1);
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function DeleteSkill(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteSkill'](arg1, arg2, arg3);
}

export function ExportConfig(arg1, arg2) {
  return window['go']['main']['App']['ExportConfig'](arg1, arg2);
}

export function GetCodexProfiles() {
  return window['go']['main']['App']['GetCodexProfiles']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportConfig(arg1) {
  return window['go']['main']['App']['ImportConfig'](arg1);
}

export function ListMCPToolsAndResources(arg1) {
  return window['go']['main']['App']['ListMCPToolsAndResources'](arg1);
}

export function ListSkills(arg1, arg2) {
  return window['go']['main']['App']['ListSkills'](arg1, arg2);
}

export function OpenClaudeFolder() {
  return window['go']['main']['App']['OpenClaudeFolder']();
}

export function OpenInExplorer(arg1) {
  return window['go']['main']['App']['OpenInExplorer'](arg1);
}

export function OpenSkillsFolder() {
  return window['go']['main']['App']['OpenSkillsFolder']();
}

export function PickDirectory(arg1) {
  return window['go']['main']['App']['PickDirectory'](arg1);
}

export function PickFile(arg1, arg2) {
  return window['go']['main']['App']['PickFile'](arg1, arg2);
}

export function ReadConfigFile(arg1) {
  return window['go']['main']['App']['ReadConfigFile'](arg1);
}

export function ResetConfig() {
  return window['go']['main']['App']['ResetConfig']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveSkill(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSkill'](arg1, arg2, arg3);
}

export function SwitchCodexProfile(arg1) {
  return window['go']['main']['App']['SwitchCodexProfile'](arg1);
}

export function TestMCPConnection(arg1) {
  return window['go']['main']['App']['TestMCPConnection'](arg1);
}

export function WriteConfigFile(arg1, arg2) {
  return window['go']['main']['App']['WriteConfigFile'](arg1, arg2);
}
