// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {mcp} from '../models';
import {skills} from '../models';

export function ApplyProviderProfile(arg1:Record<string, any>):Promise<config.ApplyResult>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function DeleteSkill(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ExportConfig(arg1:Record<string, any>,arg2:string):Promise<void>;

export function GetConfig():Promise<Record<string, any>>;

export function GetConfigPath():Promise<string>;

export function GetVersion():Promise<Record<string, any>>;

export function ImportConfig(arg1:string):Promise<Record<string, any>>;

export function ListMCPToolsAndResources(arg1:Record<string, any>):Promise<mcp.ListResult>;

export function ListSkills(arg1:string,arg2:string):Promise<Array<skills.Skill>>;

export function OpenClaudeFolder():Promise<void>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function OpenSkillsFolder():Promise<void>;

export function PickDirectory(arg1:string):Promise<string>;

export function PickFile(arg1:string,arg2:string):Promise<string>;

export function ReadConfigFile(arg1:string):Promise<string>;

export function ResetConfig():Promise<Record<string, any>>;

export function SaveConfig(arg1:Record<string, any>):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<string>;

export function SaveSkill(arg1:string,arg2:string,arg3:Record<string, any>):Promise<void>;

export function TestMCPConnection(arg1:Record<string, any>):Promise<mcp.TestResult>;

export function WriteConfigFile(arg1:string,arg2:string):Promise<Record<string, any>>;
